### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by nightvision04** [Boulder-Investment-Technologies/lppls#28]
Currently we only platform test for `ubuntu-latest`.  Could we expand the yml to include `windows-latest`?

**Comment by Joshwani** [comment]
Yeah, definitely, is that as simple as adding it to the .yml?

**Comment by nightvision04** [comment]
Yep. You can test ubuntu-latest and windows-latest in the "steps" of a matrix strategy (big ol' for-loop). 

What I recommend is using is essentially something with this syntax:

```jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - id: step1
      run: echo "::set-output name=test::hello"
    - id: step2
      run: echo "::set-output name=test::lppls for ubuntu"
  job2:
    runs-on: windows-latest
    needs: job1
    steps:
    - id: step1
      run: echo "::set-output name=test::hello"
    - id: step2
      run: echo "::set-output name=test::lppls for windows"

**Comment by nightvision04** [comment]
A pretty good article has been written here about it:

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

**Comment by nightvision04** [comment]
If you want to get fancy with supporting multiple python versions on each, then it looks more like this:

```
  job1:
    runs-on: ubuntu-latest
    strategy:
          matrix:
            python-version: [3.6, 3.7, 3.8]
    steps:
    - id: step1
      run: echo "::set-output name=test::lppls for ubuntu"

  job2:
    runs-on: windows-latest
    strategy:
          matrix:
            python-version: [3.6, 3.7, 3.8]
    steps:
    - id: step1
      run: echo "::set-output name=test::lppls for windows"
```
